//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArquivoSecao
    {
        public ArquivoSecao()
        {
            this.Arquivo = new HashSet<Arquivo>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Caminho { get; set; }
        public System.DateTime Atualizacao { get; set; }
    
        public virtual ICollection<Arquivo> Arquivo { get; set; }
    }
}
