//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Taxa = new HashSet<Taxa>();
            this.Lancamento = new HashSet<Lancamento>();
            this.Bonificacao = new HashSet<Bonificacao>();
        }
    
        public int ID { get; set; }
        public int TipoID { get; set; }
        public string Nome { get; set; }
    
        public virtual CategoriaTipo CategoriaTipo { get; set; }
        public virtual ICollection<Taxa> Taxa { get; set; }
        public virtual ICollection<Lancamento> Lancamento { get; set; }
        public virtual ICollection<Bonificacao> Bonificacao { get; set; }
    }
}
