//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public Endereco()
        {
            this.Motivacard = new HashSet<Motivacard>();
            this.Pedido = new HashSet<Pedido>();
            this.Pedido1 = new HashSet<Pedido>();
        }
    
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public string Nome { get; set; }
        public int EstadoID { get; set; }
        public int CidadeID { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Distrito { get; set; }
        public string CodigoPostal { get; set; }
        public string Observacoes { get; set; }
        public bool Principal { get; set; }
        public string CidadeNome { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Motivacard> Motivacard { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<Pedido> Pedido1 { get; set; }
    }
}
