//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instituicao
    {
        public Instituicao()
        {
            this.ContaDeposito = new HashSet<ContaDeposito>();
        }
    
        public int ID { get; set; }
        public int IDPais { get; set; }
        public int IDAtivo { get; set; }
        public string CodigoInstituicao { get; set; }
        public string Descricao { get; set; }
    
        public virtual Ativo Ativo { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<ContaDeposito> ContaDeposito { get; set; }
    }
}
