//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAcesso
    {
        public int ID { get; set; }
        public System.DateTime DATA { get; set; }
        public string IP { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
    }
}
