//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Estados = new HashSet<Estado>();
            this.Usuarios = new HashSet<Usuario>();
            this.Armazem = new HashSet<Armazem>();
            this.Administrador = new HashSet<Administrador>();
            this.Instituicao = new HashSet<Instituicao>();
        }
    
        public int ID { get; set; }
        public int BlocoID { get; set; }
        public int IdiomaID { get; set; }
        public int MoedaID { get; set; }
        public string Sigla { get; set; }
        public string Nome { get; set; }
        public bool Padrao { get; set; }
        public bool Disponivel { get; set; }
        public string MascaraTel { get; set; }
        public string MascaraCel { get; set; }
        public string MascaraCep { get; set; }
    
        public virtual Bloco Bloco { get; set; }
        public virtual ICollection<Estado> Estados { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public virtual ICollection<Armazem> Armazem { get; set; }
        public virtual ICollection<Administrador> Administrador { get; set; }
        public virtual ICollection<Instituicao> Instituicao { get; set; }
    }
}
