//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoPagamento
    {
        public PedidoPagamento()
        {
            this.Boleto = new HashSet<Boleto>();
            this.PedidoPagamentoStatus = new HashSet<PedidoPagamentoStatus>();
        }
    
        public int ID { get; set; }
        public int PedidoID { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<int> ContaID { get; set; }
        public int MoedaID { get; set; }
        public int MeioPagamentoID { get; set; }
        public int FormaPagamentoID { get; set; }
        public int ReferenciaID { get; set; }
        public string Numero { get; set; }
        public string Mensagem { get; set; }
        public Nullable<double> Valor { get; set; }
        public int MoedaIDCripto { get; set; }
        public Nullable<double> ValorCripto { get; set; }
        public Nullable<double> CotacaoCripto { get; set; }
    
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual Conta Conta { get; set; }
        public virtual Moeda Moeda { get; set; }
        public virtual Moeda Moeda1 { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<PedidoPagamentoStatus> PedidoPagamentoStatus { get; set; }
    }
}
