//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicao
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int ReferenciaID { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public Nullable<double> ValorPernaEsquerda { get; set; }
        public Nullable<double> ValorPernaDireita { get; set; }
        public Nullable<double> AcumuladoEsquerda { get; set; }
        public Nullable<double> AcumuladoDireita { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<double> ValorDiaPernaEsquerda { get; set; }
        public Nullable<double> ValorDiaPernaDireita { get; set; }
        public Nullable<int> QualificadorEsquerdoID { get; set; }
        public Nullable<int> QualificadorDireitoID { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
