//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoItem
    {
        public ProdutoItem()
        {
            this.PedidoItem = new HashSet<PedidoItem>();
        }
    
        public int ID { get; set; }
        public int ProdutoID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> OpcaoID { get; set; }
        public int Quantidade { get; set; }
        public string Observacao { get; set; }
    
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
        public virtual ProdutoOpcao ProdutoOpcao { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Produto Produto1 { get; set; }
    }
}
