//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualificacao
    {
        public int ID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<int> CicloID { get; set; }
        public Nullable<int> QualificadorEsquerdaID { get; set; }
        public Nullable<int> QualificadorDireitaID { get; set; }
        public Nullable<System.DateTime> DataQualificacao { get; set; }
        public Nullable<bool> Ultimo { get; set; }
    }
}
