//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedeMigracao
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int PatrocinadorID { get; set; }
        public int Linha { get; set; }
        public int Ordem { get; set; }
    }
}
