//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegraItem
    {
        public int ID { get; set; }
        public int RegraID { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> AssociacaoID { get; set; }
        public string Regra { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Ativo { get; set; }
        public Nullable<int> ClassificacaoID { get; set; }
        public Nullable<int> ClassificacaoNivel { get; set; }
    }
}
