//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sincronizacao
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int Status { get; set; }
        public System.DateTime Data { get; set; }
        public string Observacao { get; set; }
        public string UsuarioIDParceiro { get; set; }
        public int UsuarioIDIntegracao { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
