//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxa
    {
        public Taxa()
        {
            this.PedidoTaxa = new HashSet<PedidoTaxa>();
        }
    
        public int ID { get; set; }
        public int CategoriaID { get; set; }
        public int TipoID { get; set; }
        public string Nome { get; set; }
        public string TipoProdutoIDs { get; set; }
        public string AssociacaoIDs { get; set; }
        public string ClassificacaoIDs { get; set; }
        public string BlocoIDs { get; set; }
        public string PaisIDs { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<double> Valor { get; set; }
        public bool Disponivel { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<PedidoTaxa> PedidoTaxa { get; set; }
    }
}
