//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traducao
    {
        public int ID { get; set; }
        public int IdiomaID { get; set; }
        public int SecaoID { get; set; }
        public string Chave { get; set; }
        public string Texto { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> Atualizacao { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual TraducaoSecao TraducaoSecao { get; set; }
    }
}
