//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Documentos = new HashSet<Documento>();
            this.Enderecos = new HashSet<Endereco>();
            this.PatrocinadosDireto = new HashSet<Usuario>();
            this.PatrocinadosPosicao = new HashSet<Usuario>();
            this.PatrocinadoresUltimoDireita = new HashSet<Usuario>();
            this.PatrocinadoresUltimoEsquerda = new HashSet<Usuario>();
            this.UsuarioStatus = new HashSet<UsuarioStatus>();
            this.Suporte = new HashSet<Suporte>();
            this.UsuarioClassificacoes = new HashSet<UsuarioClassificacao>();
            this.Motivacards = new HashSet<Motivacard>();
            this.Sincronizacao = new HashSet<Sincronizacao>();
            this.Bancos = new HashSet<Banco>();
            this.Agendamento = new HashSet<Agendamento>();
            this.CartaoCredito = new HashSet<CartaoCredito>();
            this.MovimentoConta = new HashSet<MovimentoConta>();
            this.Posicao = new HashSet<Posicao>();
            this.UsuarioGanho = new HashSet<UsuarioGanho>();
            this.Pedido = new HashSet<Pedido>();
            this.Pontos = new HashSet<Pontos>();
            this.AvisoLido = new HashSet<AvisoLido>();
            this.AtivacaoMensal = new HashSet<AtivacaoMensal>();
            this.ContaDeposito = new HashSet<ContaDeposito>();
            this.Saque = new HashSet<Saque>();
            this.Lancamento = new HashSet<Lancamento>();
            this.PedidoPagamento = new HashSet<PedidoPagamento>();
            this.Bonificacao = new HashSet<Bonificacao>();
        }
    
        public int ID { get; set; }
        public string Assinatura { get; set; }
        public int PaisID { get; set; }
        public Nullable<int> PatrocinadorDiretoID { get; set; }
        public Nullable<int> PatrocinadorPosicaoID { get; set; }
        public Nullable<int> UltimoDireitaID { get; set; }
        public Nullable<int> UltimoEsquerdaID { get; set; }
        public int NivelAssociacao { get; set; }
        public int NivelClassificacao { get; set; }
        public int ProfundidadeRede { get; set; }
        public int DerramamentoID { get; set; }
        public int TipoID { get; set; }
        public int StatusID { get; set; }
        public int StatusCelularID { get; set; }
        public int StatusEmailID { get; set; }
        public string Nome { get; set; }
        public string NomeFantasia { get; set; }
        public string Apelido { get; set; }
        public string Celular { get; set; }
        public string Telefone { get; set; }
        public string Sexo { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public string Documento { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public Nullable<System.DateTime> UltimoLogin { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool GeraBonus { get; set; }
        public bool RecebeBonus { get; set; }
        public Nullable<int> EntradaID { get; set; }
        public bool Bloqueado { get; set; }
        public bool Oculto { get; set; }
        public string SenhaLegado { get; set; }
        public Nullable<System.DateTime> DataAtivacao { get; set; }
        public Nullable<System.DateTime> DataValidade { get; set; }
        public Nullable<System.DateTime> DataMigracao { get; set; }
        public int TipoAtivacao { get; set; }
        public int EmpresaID { get; set; }
        public int FilialID { get; set; }
        public int IdAutenticacao { get; set; }
        public Nullable<int> ExibeSaque { get; set; }
        public Nullable<int> QtdeDiretos { get; set; }
        public Nullable<System.DateTime> DataRenovacao { get; set; }
        public bool TermoAceite { get; set; }
        public Nullable<bool> RenovacaoAutomatica { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Documento> Documentos { get; set; }
        public virtual ICollection<Endereco> Enderecos { get; set; }
        public virtual ICollection<Usuario> PatrocinadosDireto { get; set; }
        public virtual Usuario PatrocinadorDireto { get; set; }
        public virtual ICollection<Usuario> PatrocinadosPosicao { get; set; }
        public virtual Usuario PatrocinadorPosicao { get; set; }
        public virtual ICollection<Usuario> PatrocinadoresUltimoDireita { get; set; }
        public virtual Usuario UltimoDireita { get; set; }
        public virtual ICollection<Usuario> PatrocinadoresUltimoEsquerda { get; set; }
        public virtual Usuario UltimoEsquerda { get; set; }
        public virtual ICollection<UsuarioStatus> UsuarioStatus { get; set; }
        public virtual ICollection<Suporte> Suporte { get; set; }
        public virtual Complemento Complemento { get; set; }
        public virtual ICollection<UsuarioClassificacao> UsuarioClassificacoes { get; set; }
        public virtual ICollection<Motivacard> Motivacards { get; set; }
        public virtual ICollection<Sincronizacao> Sincronizacao { get; set; }
        public virtual ICollection<Banco> Bancos { get; set; }
        public virtual Filial Filial { get; set; }
        public virtual Autenticacao Autenticacao { get; set; }
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual ICollection<CartaoCredito> CartaoCredito { get; set; }
        public virtual ICollection<MovimentoConta> MovimentoConta { get; set; }
        public virtual ICollection<Posicao> Posicao { get; set; }
        public virtual ICollection<UsuarioGanho> UsuarioGanho { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<Pontos> Pontos { get; set; }
        public virtual ICollection<AvisoLido> AvisoLido { get; set; }
        public virtual ICollection<AtivacaoMensal> AtivacaoMensal { get; set; }
        public virtual ICollection<ContaDeposito> ContaDeposito { get; set; }
        public virtual ICollection<Saque> Saque { get; set; }
        public virtual ICollection<Lancamento> Lancamento { get; set; }
        public virtual ICollection<PedidoPagamento> PedidoPagamento { get; set; }
        public virtual ICollection<Bonificacao> Bonificacao { get; set; }
    }
}
