//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioAssociacao
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int NivelAssociacao { get; set; }
        public System.DateTime Data { get; set; }
        public bool Manual { get; set; }
        public Nullable<bool> Upgrade { get; set; }
        public Nullable<System.DateTime> DataValidade { get; set; }
    }
}
