//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioGanho
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public Nullable<double> AcumuladoGanho { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public int Indicador { get; set; }
        public Nullable<System.DateTime> DataAtingiuLimite { get; set; }
        public bool Atual { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
