var data = [
{ id: 0, parent: null, description: "Chief Executive Officer (CEO)", email: "davidalt@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/q.png", itemTitleColor: "#4169e1", phone: "352-206-7599", title: "David Dalton", label: "David Dalton" },
{ id: 1, parent: 0, description: "Co-Presidents, Platform Products & Services Division", email: "jeanwhit@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/w.png", itemTitleColor: "#4b0082", phone: "505-791-1689", title: "Jeanna White", label: "Jeanna White" },
{ id: 2, parent: 0, description: "Sr. VP, Server & Tools Division", email: "jameholt@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/e.png", itemTitleColor: "#4b0082", phone: "262-215-7998", title: "James Holt", label: "James Holt" },
{ id: 3, parent: 1, description: "VP, Server & Tools Marketing and Solutions", email: "thomwill@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/r.png", itemTitleColor: "#4b0082", phone: "904-547-5342", title: "Thomas Williams", label: "Thomas Williams" },
{ id: 4, parent: 1, description: "GM, Infrastructure Server and IT Pro Audience Marketing", email: "davikirb@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/t.png", itemTitleColor: "#4b0082", phone: "614-395-7238", title: "David Kirby", label: "David Kirby" },
{ id: 5, parent: 2, description: "VP, Server & Tools Marketing and Solutions", email: "thomwill@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/r.png", itemTitleColor: "#4b0082", phone: "904-547-5342", title: "Thomas Williams", label: "Thomas Williams" },
{ id: 6, parent: 2, description: "GM, Infrastructure Server and IT Pro Audience Marketing", email: "davikirb@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/t.png", itemTitleColor: "#4b0082", phone: "614-395-7238", title: "David Kirby", label: "David Kirby" },
{ id: 7, parent: 4, description: "VP, Server & Tools Marketing and Solutions", email: "thomwill@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/r.png", itemTitleColor: "#4b0082", phone: "904-547-5342", title: "Thomas Williams", label: "Thomas Williams" },
{ id: 8, parent: 4, description: "GM, Infrastructure Server and IT Pro Audience Marketing", email: "davikirb@name.com", groupTitleColor: "#4169e1", image: "demo/images/photos/t.png", itemTitleColor: "#4b0082", phone: "614-395-7238", title: "David Kirby", label: "David Kirby" },
];