//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArbitragemPeriodo
    {
        public ArbitragemPeriodo()
        {
            this.Arbitragem = new HashSet<Arbitragem>();
        }
    
        public int ID { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
    
        public virtual ICollection<Arbitragem> Arbitragem { get; set; }
    }
}
