//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtivacaoMensal
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int CicloID { get; set; }
        public System.DateTime DataAtivacao { get; set; }
        public bool Ultimo { get; set; }
        public Nullable<double> Valor { get; set; }
    
        public virtual Ciclo Ciclo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
