//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviso
    {
        public Aviso()
        {
            this.AvisoLido = new HashSet<AvisoLido>();
        }
    
        public int ID { get; set; }
        public int TipoID { get; set; }
        public int IdiomaID { get; set; }
        public System.DateTime Atualizacao { get; set; }
        public string UsuarioIDs { get; set; }
        public string AssociacaoIDs { get; set; }
        public string Titulo { get; set; }
        public string Video { get; set; }
        public string Texto { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public bool Urgente { get; set; }
        public bool Bloqueado { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual AvisoTipo AvisoTipo { get; set; }
        public virtual ICollection<AvisoLido> AvisoLido { get; set; }
    }
}
