//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public Banco()
        {
            this.Saque = new HashSet<Saque>();
        }
    
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public string Dados { get; set; }
        public bool Principal { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Saque> Saque { get; set; }
    }
}
