//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitCoinSafe
    {
        public int ID { get; set; }
        public Nullable<int> PedidoID { get; set; }
        public Nullable<int> BonusID { get; set; }
        public double ValorBruto { get; set; }
        public double ValorLiquido { get; set; }
        public double Diferenca { get; set; }
        public System.DateTime Data { get; set; }
    }
}
