//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracao
    {
        public int ID { get; set; }
        public int CategoriaID { get; set; }
        public int TipoID { get; set; }
        public string Chave { get; set; }
        public string Nome { get; set; }
        public string Dados { get; set; }
    
        public virtual ConfiguracaoCategoria ConfiguracaoCategoria { get; set; }
        public virtual ConfiguracaoTipo ConfiguracaoTipo { get; set; }
    }
}
