//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<int> AdministradorID { get; set; }
        public int TipoID { get; set; }
        public bool Validado { get; set; }
        public System.DateTime DataEnvio { get; set; }
        public Nullable<System.DateTime> DataValidacao { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Administrador Administrador { get; set; }
    }
}
