//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filial
    {
        public Filial()
        {
            this.Usuario = new HashSet<Usuario>();
            this.AgendamentoItem = new HashSet<AgendamentoItem>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string NomeFantasia { get; set; }
        public int EstadoID { get; set; }
        public int CidadeID { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Distrito { get; set; }
        public string CodigoPostal { get; set; }
        public string Observacoes { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<AgendamentoItem> AgendamentoItem { get; set; }
    }
}
