//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginExterno
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int AdministradorID { get; set; }
        public System.Guid Guid { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public bool Usado { get; set; }
        public System.DateTime DataHora { get; set; }
    }
}
