//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoedaCotacao
    {
        public int ID { get; set; }
        public int MoedaOrigemID { get; set; }
        public int MoedaDestinoID { get; set; }
        public double Valor { get; set; }
        public System.DateTime Data { get; set; }
        public int TipoID { get; set; }
    
        public virtual Moeda Moeda { get; set; }
        public virtual Moeda Moeda1 { get; set; }
        public virtual MoedaCotacaoTipo MoedaCotacaoTipo { get; set; }
    }
}
