//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motivacard
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int EnderecoID { get; set; }
        public int StatusID { get; set; }
        public string NSU { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string NomeMae { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public System.DateTime DataCriacao { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
