//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoItem
    {
        public PedidoItem()
        {
            this.PedidoItem1 = new HashSet<PedidoItem>();
            this.PedidoItemStatus = new HashSet<PedidoItemStatus>();
            this.PedidoItemStatusEntrega = new HashSet<PedidoItemStatusEntrega>();
        }
    
        public int ID { get; set; }
        public int PedidoID { get; set; }
        public Nullable<int> PedidoItemID { get; set; }
        public int ProdutoID { get; set; }
        public Nullable<int> ProdutoItemID { get; set; }
        public Nullable<int> ProdutoOpcaoID { get; set; }
        public int Quantidade { get; set; }
        public Nullable<double> ValorUnitario { get; set; }
        public Nullable<double> BonificacaoUnitaria { get; set; }
    
        public virtual ICollection<PedidoItem> PedidoItem1 { get; set; }
        public virtual PedidoItem PedidoItem2 { get; set; }
        public virtual ICollection<PedidoItemStatus> PedidoItemStatus { get; set; }
        public virtual ICollection<PedidoItemStatusEntrega> PedidoItemStatusEntrega { get; set; }
        public virtual ProdutoOpcao ProdutoOpcao { get; set; }
        public virtual ProdutoItem ProdutoItem { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
