//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class YLEVELEntities : DbContext
    {
        public YLEVELEntities()
            : base("name=YLEVELEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria> Categorias { get; set; }
        public DbSet<Conta> Contas { get; set; }
        public DbSet<ContaOperacao> ContaOperacoes { get; set; }
        public DbSet<Bloco> Blocos { get; set; }
        public DbSet<Cidade> Cidades { get; set; }
        public DbSet<Estado> Estados { get; set; }
        public DbSet<Idioma> Idiomas { get; set; }
        public DbSet<Moeda> Moedas { get; set; }
        public DbSet<Pais> Paises { get; set; }
        public DbSet<Traducao> Traducoes { get; set; }
        public DbSet<ProdutoDepartamento> ProdutoDepartamentos { get; set; }
        public DbSet<Configuracao> Configuracoes { get; set; }
        public DbSet<Documento> Documentos { get; set; }
        public DbSet<Endereco> Enderecos { get; set; }
        public DbSet<UsuarioStatus> UsuarioStatus { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<UsuarioClassificacao> UsuarioClassificacoes { get; set; }
        public DbSet<Motivacard> Motivacard { get; set; }
        public DbSet<Sincronizacao> Sincronizacao { get; set; }
        public DbSet<MoedaCotacao> MoedaCotacao { get; set; }
        public DbSet<Ativo> Ativo { get; set; }
        public DbSet<Banco> Banco { get; set; }
        public DbSet<EstoqueMovimento> EstoqueMovimento { get; set; }
        public DbSet<EstoqueSaldo> EstoqueSaldo { get; set; }
        public DbSet<TipoConta> TipoConta { get; set; }
        public DbSet<Armazem> Armazem { get; set; }
        public DbSet<Filial> Filial { get; set; }
        public DbSet<Autenticacao> Autenticacao { get; set; }
        public DbSet<Agendamento> Agendamento { get; set; }
        public DbSet<AgendamentoItem> AgendamentoItem { get; set; }
        public DbSet<LogAcesso> LogAcesso { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<ConfiguracaoBonusCarreira> ConfiguracaoBonusCarreira { get; set; }
        public DbSet<ConfiguracaoBonusDiario> ConfiguracaoBonusDiario { get; set; }
        public DbSet<ConfiguracaoCategoria> ConfiguracaoCategoria { get; set; }
        public DbSet<ConfiguracaoTipo> ConfiguracaoTipo { get; set; }
        public DbSet<Paginacao> Paginacao { get; set; }
        public DbSet<CategoriaTipo> CategoriaTipo { get; set; }
        public DbSet<ProdutoCategoria> ProdutoCategoria { get; set; }
        public DbSet<TraducaoSecao> TraducaoSecao { get; set; }
        public DbSet<MoedaCotacaoTipo> MoedaCotacaoTipo { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<Administrador> Administrador { get; set; }
        public DbSet<MeioPagamento> MeioPagamento { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<BitCoinSafe> BitCoinSafe { get; set; }
        public DbSet<BlockchainLog> BlockchainLog { get; set; }
        public DbSet<UsuarioDerramamentoLog> UsuarioDerramamentoLog { get; set; }
        public DbSet<PontosBinario> PontosBinario { get; set; }
        public DbSet<ArbitragemPeriodo> ArbitragemPeriodo { get; set; }
        public DbSet<Arbitragem> Arbitragem { get; set; }
        public DbSet<Boleto> Boleto { get; set; }
        public DbSet<Suporte> Suporte { get; set; }
        public DbSet<Complemento> Complemento { get; set; }
        public DbSet<RedeMigracao> RedeMigracao { get; set; }
        public DbSet<LoginExterno> LoginExterno { get; set; }
        public DbSet<SuporteMensagem> SuporteMensagem { get; set; }
        public DbSet<CartaoCredito> CartaoCredito { get; set; }
        public DbSet<IR> IR { get; set; }
        public DbSet<MovimentoConta> MovimentoConta { get; set; }
        public DbSet<Cupom> Cupom { get; set; }
        public DbSet<PedidoTaxa> PedidoTaxa { get; set; }
        public DbSet<Taxa> Taxa { get; set; }
        public DbSet<Posicao> Posicao { get; set; }
        public DbSet<PedidoItem> PedidoItem { get; set; }
        public DbSet<PedidoItemStatus> PedidoItemStatus { get; set; }
        public DbSet<PedidoItemStatusEntrega> PedidoItemStatusEntrega { get; set; }
        public DbSet<ProdutoOpcao> ProdutoOpcao { get; set; }
        public DbSet<Instituicao> Instituicao { get; set; }
        public DbSet<ProdutoItem> ProdutoItem { get; set; }
        public DbSet<ProdutoValor> ProdutoValor { get; set; }
        public DbSet<Associacao> Associacao { get; set; }
        public DbSet<AssociacaoLimiteGanho> AssociacaoLimiteGanho { get; set; }
        public DbSet<Classificacao> Classificacao { get; set; }
        public DbSet<UsuarioGanho> UsuarioGanho { get; set; }
        public DbSet<Pedido> Pedido { get; set; }
        public DbSet<Integracao> Integracao { get; set; }
        public DbSet<ArquivoSecao> ArquivoSecao { get; set; }
        public DbSet<ArquivoTipo> ArquivoTipo { get; set; }
        public DbSet<Arquivo> Arquivo { get; set; }
        public DbSet<Produto> Produto { get; set; }
        public DbSet<ProdutoTipo> ProdutoTipo { get; set; }
        public DbSet<SaqueStatus> SaqueStatus { get; set; }
        public DbSet<Ciclo> Ciclo { get; set; }
        public DbSet<Pontos> Pontos { get; set; }
        public DbSet<Aviso> Aviso { get; set; }
        public DbSet<AvisoLido> AvisoLido { get; set; }
        public DbSet<AvisoTipo> AvisoTipo { get; set; }
        public DbSet<AtivacaoMensal> AtivacaoMensal { get; set; }
        public DbSet<Qualificacao> Qualificacao { get; set; }
        public DbSet<UsuarioAssociacao> UsuarioAssociacao { get; set; }
        public DbSet<LancamentoTipo> LancamentoTipo { get; set; }
        public DbSet<ContaDeposito> ContaDeposito { get; set; }
        public DbSet<Saque> Saque { get; set; }
        public DbSet<Lancamento> Lancamento { get; set; }
        public DbSet<PedidoPagamento> PedidoPagamento { get; set; }
        public DbSet<PedidoPagamentoStatus> PedidoPagamentoStatus { get; set; }
        public DbSet<Bonificacao> Bonificacao { get; set; }
        public DbSet<SplitCripto> SplitCripto { get; set; }
    
        public virtual ObjectResult<spPontuacaoPosicao_Result> spPontuacaoPosicao(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPontuacaoPosicao_Result>("spPontuacaoPosicao", idUsuarioParameter);
        }
    
        public virtual ObjectResult<spC_ObtemDiretos_Result> spC_ObtemDiretos(Nullable<int> id, Nullable<int> idUsuario, Nullable<int> nivelPai, Nullable<int> maxNivel, Nullable<int> exibeNivel)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var nivelPaiParameter = nivelPai.HasValue ?
                new ObjectParameter("NivelPai", nivelPai) :
                new ObjectParameter("NivelPai", typeof(int));
    
            var maxNivelParameter = maxNivel.HasValue ?
                new ObjectParameter("MaxNivel", maxNivel) :
                new ObjectParameter("MaxNivel", typeof(int));
    
            var exibeNivelParameter = exibeNivel.HasValue ?
                new ObjectParameter("ExibeNivel", exibeNivel) :
                new ObjectParameter("ExibeNivel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spC_ObtemDiretos_Result>("spC_ObtemDiretos", idParameter, idUsuarioParameter, nivelPaiParameter, maxNivelParameter, exibeNivelParameter);
        }
    
        public virtual ObjectResult<spC_AtivoMensal_Result> spC_AtivoMensal(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spC_AtivoMensal_Result>("spC_AtivoMensal", idParameter);
        }
    
        public virtual ObjectResult<spOC_US_ObtemAvisoNaoLidos_Result> spOC_US_ObtemAvisoNaoLidos(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spOC_US_ObtemAvisoNaoLidos_Result>("spOC_US_ObtemAvisoNaoLidos", usuarioIdParameter);
        }
    
        public virtual ObjectResult<spOC_US_ObtemAvisos_Result> spOC_US_ObtemAvisos(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spOC_US_ObtemAvisos_Result>("spOC_US_ObtemAvisos", usuarioIdParameter);
        }
    }
}
