//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armazem
    {
        public Armazem()
        {
            this.EstoqueMovimento = new HashSet<EstoqueMovimento>();
            this.EstoqueSaldo = new HashSet<EstoqueSaldo>();
        }
    
        public int ID { get; set; }
        public string Identificador { get; set; }
        public string CNPJ { get; set; }
        public string Descricao { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public int CidadeID { get; set; }
        public int EstadoID { get; set; }
        public int PaisID { get; set; }
        public string CodigoPostal { get; set; }
        public bool Publicado { get; set; }
        public string Responsavel { get; set; }
        public string Telefone { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataPublicacao { get; set; }
        public int UsuarioID { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<EstoqueMovimento> EstoqueMovimento { get; set; }
        public virtual ICollection<EstoqueSaldo> EstoqueSaldo { get; set; }
    }
}
