//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvisoLido
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int AvisoID { get; set; }
        public System.DateTime DataLeitura { get; set; }
        public bool AvisoExcluido { get; set; }
    
        public virtual Aviso Aviso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
