//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContaOperacao
    {
        public int ID { get; set; }
        public int ContaID { get; set; }
        public int OperacaoID { get; set; }
    
        public virtual Conta Conta { get; set; }
    }
}
