//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moeda
    {
        public Moeda()
        {
            this.Contas = new HashSet<Conta>();
            this.Paises = new HashSet<Pais>();
            this.MoedaCotacao = new HashSet<MoedaCotacao>();
            this.MoedaCotacao1 = new HashSet<MoedaCotacao>();
            this.ContaDeposito = new HashSet<ContaDeposito>();
            this.Saque = new HashSet<Saque>();
            this.Saque1 = new HashSet<Saque>();
            this.PontosBinario = new HashSet<PontosBinario>();
            this.Lancamento = new HashSet<Lancamento>();
            this.PedidoPagamento = new HashSet<PedidoPagamento>();
            this.PedidoPagamento1 = new HashSet<PedidoPagamento>();
            this.Bonificacao = new HashSet<Bonificacao>();
            this.SplitCripto = new HashSet<SplitCripto>();
            this.SplitCripto1 = new HashSet<SplitCripto>();
        }
    
        public int ID { get; set; }
        public string Simbolo { get; set; }
        public string Nome { get; set; }
        public string Sigla { get; set; }
        public string MascaraIn { get; set; }
        public string MascaraOut { get; set; }
    
        public virtual ICollection<Conta> Contas { get; set; }
        public virtual ICollection<Pais> Paises { get; set; }
        public virtual ICollection<MoedaCotacao> MoedaCotacao { get; set; }
        public virtual ICollection<MoedaCotacao> MoedaCotacao1 { get; set; }
        public virtual ICollection<ContaDeposito> ContaDeposito { get; set; }
        public virtual ICollection<Saque> Saque { get; set; }
        public virtual ICollection<Saque> Saque1 { get; set; }
        public virtual ICollection<PontosBinario> PontosBinario { get; set; }
        public virtual ICollection<Lancamento> Lancamento { get; set; }
        public virtual ICollection<PedidoPagamento> PedidoPagamento { get; set; }
        public virtual ICollection<PedidoPagamento> PedidoPagamento1 { get; set; }
        public virtual ICollection<Bonificacao> Bonificacao { get; set; }
        public virtual ICollection<SplitCripto> SplitCripto { get; set; }
        public virtual ICollection<SplitCripto> SplitCripto1 { get; set; }
    }
}
