//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontosLinha
    {
        public long ID { get; set; }
        public int UsuarioID { get; set; }
        public int DiretoID { get; set; }
        public int CicloID { get; set; }
        public int VP { get; set; }
        public int VBQ { get; set; }
        public int VG { get; set; }
        public int VML { get; set; }
        public int VQ { get; set; }
        public int VPQ { get; set; }
        public int VGQ { get; set; }
        public Nullable<int> VTQ { get; set; }
        public Nullable<int> VB { get; set; }
        public Nullable<int> VT { get; set; }
    }
}
