//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pontos
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int CicloID { get; set; }
        public int VP { get; set; }
        public Nullable<int> VT { get; set; }
        public int VQ { get; set; }
        public int VB { get; set; }
        public int VL { get; set; }
        public Nullable<int> VKI { get; set; }
        public int VPQ { get; set; }
        public int VLQ { get; set; }
        public Nullable<int> VBQ { get; set; }
        public Nullable<int> VKIQ { get; set; }
        public Nullable<int> VTQ { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
