//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoValor
    {
        public int ID { get; set; }
        public int ProdutoID { get; set; }
        public Nullable<int> OpcaoID { get; set; }
        public string ContaIDs { get; set; }
        public string AssociacaoIDs { get; set; }
        public string ClassificacaoIDs { get; set; }
        public string BlocoIDs { get; set; }
        public string PaisIDs { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<double> Bonificacao { get; set; }
        public Nullable<double> VlrBonusVenda { get; set; }
        public Nullable<double> VlrBonusAdicionalVenda { get; set; }
    
        public virtual ProdutoOpcao ProdutoOpcao { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
