//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoOpcao
    {
        public ProdutoOpcao()
        {
            this.PedidoItem = new HashSet<PedidoItem>();
            this.ProdutoItem = new HashSet<ProdutoItem>();
            this.ProdutoValor = new HashSet<ProdutoValor>();
        }
    
        public int ID { get; set; }
        public string SKU { get; set; }
        public int ProdutoID { get; set; }
        public int NivelAssociacao { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<double> Peso { get; set; }
        public int Ordem { get; set; }
        public int Estoque { get; set; }
        public bool Publicado { get; set; }
    
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
        public virtual ICollection<ProdutoItem> ProdutoItem { get; set; }
        public virtual ICollection<ProdutoValor> ProdutoValor { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
