//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.AgendamentoItem = new HashSet<AgendamentoItem>();
            this.EstoqueMovimento = new HashSet<EstoqueMovimento>();
            this.EstoqueSaldo = new HashSet<EstoqueSaldo>();
            this.PedidoItem = new HashSet<PedidoItem>();
            this.ProdutoDepartamento = new HashSet<ProdutoDepartamento>();
            this.ProdutoItem = new HashSet<ProdutoItem>();
            this.ProdutoItem1 = new HashSet<ProdutoItem>();
            this.ProdutoOpcao = new HashSet<ProdutoOpcao>();
            this.ProdutoValor = new HashSet<ProdutoValor>();
        }
    
        public int ID { get; set; }
        public string SKU { get; set; }
        public int TipoID { get; set; }
        public int NivelAssociacao { get; set; }
        public string Nome { get; set; }
        public string Chamada { get; set; }
        public string Descricao { get; set; }
        public Nullable<double> Peso { get; set; }
        public bool Destaque { get; set; }
        public Nullable<int> LimitePorUsuario { get; set; }
        public Nullable<int> LimitePorPedido { get; set; }
        public bool ControlaEstoque { get; set; }
        public int Estoque { get; set; }
        public bool Publicado { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataPublicacao { get; set; }
        public bool VendaDireta { get; set; }
        public string Observacao { get; set; }
        public int ProdutoCategoriaID { get; set; }
        public string Dimensoes { get; set; }
        public bool AtivoMensal { get; set; }
        public bool Composto { get; set; }
        public string CodigoExterno { get; set; }
    
        public virtual ICollection<AgendamentoItem> AgendamentoItem { get; set; }
        public virtual ICollection<EstoqueMovimento> EstoqueMovimento { get; set; }
        public virtual ICollection<EstoqueSaldo> EstoqueSaldo { get; set; }
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
        public virtual ProdutoCategoria ProdutoCategoria { get; set; }
        public virtual ProdutoTipo ProdutoTipo { get; set; }
        public virtual ICollection<ProdutoDepartamento> ProdutoDepartamento { get; set; }
        public virtual ICollection<ProdutoItem> ProdutoItem { get; set; }
        public virtual ICollection<ProdutoItem> ProdutoItem1 { get; set; }
        public virtual ICollection<ProdutoOpcao> ProdutoOpcao { get; set; }
        public virtual ICollection<ProdutoValor> ProdutoValor { get; set; }
    }
}
