//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuporteMensagem
    {
        public int ID { get; set; }
        public System.Guid Guid { get; set; }
        public int SuporteID { get; set; }
        public Nullable<int> AdministradorID { get; set; }
        public string Texto { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Suporte Suporte { get; set; }
        public virtual Administrador Administrador { get; set; }
    }
}
