//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public Administrador()
        {
            this.Documento = new HashSet<Documento>();
            this.UsuarioStatus = new HashSet<UsuarioStatus>();
            this.PedidoItemStatus = new HashSet<PedidoItemStatus>();
            this.SaqueStatus = new HashSet<SaqueStatus>();
            this.SuporteMensagem = new HashSet<SuporteMensagem>();
            this.PedidoPagamentoStatus = new HashSet<PedidoPagamentoStatus>();
        }
    
        public int ID { get; set; }
        public int IdAutenticacao { get; set; }
        public int EmpresaID { get; set; }
        public string BlocoIDs { get; set; }
        public int PaisIDs { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public bool Liberado { get; set; }
        public Nullable<System.DateTime> UltimoLogin { get; set; }
    
        public virtual Autenticacao Autenticacao { get; set; }
        public virtual Autenticacao Autenticacao1 { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<UsuarioStatus> UsuarioStatus { get; set; }
        public virtual ICollection<PedidoItemStatus> PedidoItemStatus { get; set; }
        public virtual ICollection<SaqueStatus> SaqueStatus { get; set; }
        public virtual ICollection<SuporteMensagem> SuporteMensagem { get; set; }
        public virtual ICollection<PedidoPagamentoStatus> PedidoPagamentoStatus { get; set; }
    }
}
