//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendamentoItem
    {
        public AgendamentoItem()
        {
            this.Agendamento = new HashSet<Agendamento>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public int FilialID { get; set; }
        public System.DateTime Data { get; set; }
        public int ProdutoID { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fim { get; set; }
        public string De { get; set; }
        public string Ate { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
