//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendamento
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int TipoID { get; set; }
        public int AgendamentoItem { get; set; }
        public System.DateTime Data { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public int Status { get; set; }
        public int PedidoID { get; set; }
    
        public virtual AgendamentoItem AgendamentoItem1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
