//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arbitragem
    {
        public int ID { get; set; }
        public int ArbitragemPeriodoID { get; set; }
        public int NivelAssociacao { get; set; }
        public Nullable<double> PercentualDomingo { get; set; }
        public Nullable<double> PercentualSegunda { get; set; }
        public Nullable<double> PercentualTerca { get; set; }
        public Nullable<double> PercentualQuarta { get; set; }
        public Nullable<double> PercentualQuinta { get; set; }
        public Nullable<double> PercentualSexta { get; set; }
        public Nullable<double> PercentualSabado { get; set; }
    
        public virtual ArbitragemPeriodo ArbitragemPeriodo { get; set; }
    }
}
