//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arquivo
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int SecaoID { get; set; }
        public int TipoID { get; set; }
        public bool Ativo { get; set; }
        public System.DateTime Atualizacao { get; set; }
        public string Imagem { get; set; }
        public string Observacao { get; set; }
    
        public virtual ArquivoSecao ArquivoSecao { get; set; }
        public virtual ArquivoTipo ArquivoTipo { get; set; }
    }
}
