//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        public int ID { get; set; }
        public int PedidoPagamentoID { get; set; }
        public int StatusID { get; set; }
        public string NossoNumero { get; set; }
        public int NumeroDocumento { get; set; }
        public Nullable<double> ValorTotal { get; set; }
        public Nullable<double> ValorPago { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
    
        public virtual PedidoPagamento PedidoPagamento { get; set; }
    }
}
