//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificacaoVML
    {
        public int ID { get; set; }
        public int ClassificacaoID { get; set; }
        public int LinhaMinimo { get; set; }
        public decimal VML { get; set; }
        public int NiveisAbertos { get; set; }
    }
}
