//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracaoTipo
    {
        public ConfiguracaoTipo()
        {
            this.Configuracao = new HashSet<Configuracao>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Configuracao> Configuracao { get; set; }
    }
}
