//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracaoBonusCarreira
    {
        public int ID { get; set; }
        public System.DateTime DataReferencia { get; set; }
        public Nullable<int> CarreiraID { get; set; }
        public double Valor { get; set; }
        public Nullable<int> QuantidadePessoas { get; set; }
    }
}
