//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int ID { get; set; }
        public System.DateTime Atualizacao { get; set; }
        public bool Ativo { get; set; }
        public bool TermoAceite { get; set; }
        public System.DateTime DataValidade { get; set; }
        public string Nome { get; set; }
        public string NomeFantasia { get; set; }
        public string Documento { get; set; }
        public string Responsavel { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public int PaisID { get; set; }
        public int EstadoID { get; set; }
        public int CidadeID { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Distrito { get; set; }
        public string CodigoPostal { get; set; }
        public string EstadoNome { get; set; }
        public string CidadeNome { get; set; }
        public string Observacao { get; set; }
    }
}
