//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IR
    {
        public int ID { get; set; }
        public Nullable<double> Inicial { get; set; }
        public Nullable<double> Final { get; set; }
        public Nullable<double> Deduzir { get; set; }
        public Nullable<double> Aliquota { get; set; }
    }
}
