//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Agendamento = new HashSet<Agendamento>();
            this.PedidoItem = new HashSet<PedidoItem>();
            this.PedidoTaxa = new HashSet<PedidoTaxa>();
            this.Lancamento = new HashSet<Lancamento>();
            this.PedidoPagamento = new HashSet<PedidoPagamento>();
            this.Bonificacao = new HashSet<Bonificacao>();
            this.SplitCripto = new HashSet<SplitCripto>();
        }
    
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<int> EnderecoFaturamentoID { get; set; }
        public Nullable<int> EnderecoEntregaID { get; set; }
        public Nullable<int> CupomID { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> Total { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public string Observacoes { get; set; }
        public Nullable<int> UsuarioIDOrigem { get; set; }
        public int TipoEntregaID { get; set; }
        public Nullable<int> ArmazemEntregaID { get; set; }
        public Nullable<int> QuantidadeAgendamento { get; set; }
        public Nullable<System.DateTime> DataIntegracao { get; set; }
        public double ValorFrete { get; set; }
        public double ValorJuros { get; set; }
        public int Parcelamento { get; set; }
        public Nullable<int> PedidoExternoID { get; set; }
        public Nullable<int> CicloID { get; set; }
    
        public virtual ICollection<Agendamento> Agendamento { get; set; }
        public virtual Cupom Cupom { get; set; }
        public virtual Endereco EnderecoEntrega { get; set; }
        public virtual Endereco EnderecoFaturamento { get; set; }
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
        public virtual ICollection<PedidoTaxa> PedidoTaxa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Lancamento> Lancamento { get; set; }
        public virtual ICollection<PedidoPagamento> PedidoPagamento { get; set; }
        public virtual ICollection<Bonificacao> Bonificacao { get; set; }
        public virtual ICollection<SplitCripto> SplitCripto { get; set; }
    }
}
