//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suporte
    {
        public Suporte()
        {
            this.SuporteMensagem = new HashSet<SuporteMensagem>();
        }
    
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public System.DateTime Data { get; set; }
        public string Assunto { get; set; }
        public bool Respondido { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<SuporteMensagem> SuporteMensagem { get; set; }
    }
}
